MeuSiteEmMVC/MeuSiteEmMVC/Controllers/ContatoController.cs
using MeuSiteEmMVC.Data;
using MeuSiteEmMVC.Filters;
using MeuSiteEmMVC.Models;
using MeuSiteEmMVC.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace MeuSiteEmMVC.Controllers;

[FiltroLogado]
public class ContatoController : Controller
{
    // campo (guarda um objeto que implementa a interface)
    private readonly IContatoRepositorio _contatoRepositorio;

    public ContatoController(IContatoRepositorio contatoRepositorio)
    {
        _contatoRepositorio = contatoRepositorio;
    }

    public IActionResult Index()
    {
        List<ContatoModel> contatos = _contatoRepositorio.BuscarTodos();
        return View(contatos);
    }

    public IActionResult Criar()
    {
        return View();
    }

    [HttpPost] // posso criar um método de mesmo nome porém o método HTTP precisa ser diferente
    public IActionResult Criar(ContatoModel contato)
    {
        // verifica se os dados são válidos de acordo com o data annotation na model
        try
        {
            if (ModelState.IsValid)
            {
                _contatoRepositorio.Adicionar(contato);
                TempData["MensagemSucesso"] = $"{contato.Nome} foi adicionado com sucesso a sua lista de contatos.";
            }
            return RedirectToAction("Index");
        }
        catch (Exception err)
        {
            TempData["MensagemErro"] = $"Erro criar contato: {err.Message}";
            return RedirectToAction("Index");
        }
    }

    public IActionResult Editar(int id)
    {
        ContatoModel contato = _contatoRepositorio.ListarPorId(id);
        return View(contato);
    }

    [HttpPost]
    public IActionResult Editar(ContatoModel contato)
    {
        try
        {
            if (ModelState.IsValid)
            {
                _contatoRepositorio.Atualizar(contato); // verificar se houve alterações
                TempData["MensagemSucesso"] = $"O contato {contato.Nome} foi alterado com sucesso";
                return RedirectToAction("Index");
            }
            return View(contato);
        }
        catch (Exception err)
        {
            TempData["MensagemErro"] = $"Erro ao editar contato";
            return RedirectToAction("Index");
        }
    }

    public IActionResult Apagar(int id)
    {
        ContatoModel contato = _contatoRepositorio.ListarPorId(id);
        return View(contato);
    }

    public IActionResult ApagarConfirma(int id)
    {
        try
        {
            bool apagado = _contatoRepositorio.Apagar(id);
            if (apagado)
            {
                TempData["MensagemSucesso"] = $"Contato removido com sucesso";
            }
            else
            {
                TempData["MensagemErro"] = $"Erro ao remover contato";
            }
            return RedirectToAction("Index");
        }
        catch (Exception err)
        {
            TempData["MensagemErro"] = $"Erro ao remover contato: {err.Message}";
            return RedirectToAction("Index");
        }
    }

}

MeuSiteEmMVC/MeuSiteEmMVC/Controllers/UsuarioController.cs
using MeuSiteEmMVC.Filters;
using MeuSiteEmMVC.Models;
using MeuSiteEmMVC.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace MeuSiteEmMVC.Controllers;

[FiltroAdmin]
public class UsuarioController : Controller
{
    private readonly IUsuarioRepositorio _usuarioRepositorio;

    public UsuarioController(IUsuarioRepositorio usuarioRepositorio)
    {
        _usuarioRepositorio = usuarioRepositorio;
    }

    public IActionResult Index()
    {
        List<UsuarioModel> usuarios = _usuarioRepositorio.BuscarTodos();
        return View(usuarios);
    }

    public IActionResult Criar()
    { // essa view usa a model nos valores dos campos
        // porém como aqui não é passado uma model os campos começam vazios
        return View();
    }

    [HttpPost]
    public IActionResult Criar(UsuarioModel usuario)
    {
        try
        {
            if (ModelState.IsValid)
            {
                usuario = _usuarioRepositorio.Adicionar(usuario);
                TempData["MensagemSucesso"] = "Usuário Adicionado com sucesso";
                return RedirectToAction("Index");
            }

            return View(usuario);
        }
        catch (Exception ex)
        {
            TempData["MensagemErro"] = "Erro ao adicionar usuário";
            return RedirectToAction("Index");
        }
    }

    public IActionResult Editar(int id)
    {
        UsuarioModel usuario = _usuarioRepositorio.ListarPorId(id);
        return View(usuario);
    }


    [HttpPost]
    public IActionResult Editar(UsuarioModel usuario)
    {
        try
        {
            ModelState.Remove("Senha");

            if (ModelState.IsValid)
            {
                UsuarioModel usuarioAtualizado = new UsuarioModel()
                {
                    Id = usuario.Id,
                    Nome = usuario.Nome,
                    Login = usuario.Login,
                    Email = usuario.Email,
                    Perfil = usuario.Perfil
                };

                usuarioAtualizado = _usuarioRepositorio.Atualizar(usuario);
                TempData["MensagemSucesso"] = "Usuário Atualizado com Sucesso";
                return RedirectToAction("Index");
            }

            return View(usuario);
        }
        catch (Exception ex)
        {
            TempData["MensagemErro"] = "Não conseguimos atulizar o usuáiro";
            return View("Index");
        }
    }

    public IActionResult ApagarUsuario(int id)
    {
        var usuario = _usuarioRepositorio.ListarPorId(id);
        if (usuario == null)
        {
            TempData["MensagemErro"] = "Usuário não encontrado";
            return RedirectToAction("Index");
        }

        return View(usuario);

    }

    public IActionResult ApagarConfirma(int id)
    {
        bool sucecess = _usuarioRepositorio.Apagar(id);

        if (sucecess)
        {
            TempData["MensagemSucesso"] = "Usuário removido com sucesso";
        }

        return RedirectToAction("Index");
    }
}

MeuSiteEmMVC/MeuSiteEmMVC/Views/Usuario/ApagarUsuario.cshtml
@model UsuarioModel
@{
    ViewData["Title"] = "Excluir Usuário";
}

<section class="text-center">
    <div class="text-center">
        <h3>Tem certeza que deseja excluir o usuário (@Model.Nome)?</h3>
    </div>
    <a class="btn-primary btn" role="button" asp-controller="Usuario" asp-action="Index">Cancelar </a>
    <a class="btn-danger btn" role="button" asp-route-id="@Model.Id" asp-controller="Usuario" asp-action="ApagarConfirma">Excluir </a>
</section>

MeuSiteEmMVC/MeuSiteEmMVC/Views/Usuario/Criar.cshtml
@using MeuSiteEmMVC.Enums
@model UsuarioModel
@{
    ViewData["Title"] = "Criar Usuario";
}

<div class="text-center">
    <h1 class="display-4">Cadastrar usuario</h1>
</div>
<form asp-controller="Usuario" asp-action="Criar" method="post">
    <div class="mb-3">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" asp-for="Nome" id="nome" class="form-control" placeholder="Digite o nome do usuario">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="text" asp-for="Email" id="email" class="form-control" placeholder="Digite o email do usuario">
        @Html.ValidationMessageFor(x => x.Email)
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">Login</label>
        <input type="text" asp-for="Login" id="login" class="form-control" placeholder="Digite o login do usuario">
        @Html.ValidationMessageFor(x => x.Login)
    </div>
    <div class="mb-3">
        <label for="perfil" class="form-label">Perfil</label>
        <select asp-for="Perfil" class="form-control" id="perfil">
            <option value="">Selecione</option>
            <option value="@PerfilEnum.Admin">Administrador</option>
            <option value="@PerfilEnum.Padrao">Padrão</option>
        </select>
        @Html.ValidationMessageFor(x => x.Perfil)
    </div>
    <div class="mb-3">
        <label for="telefone" class="form-label">Senha</label>
        <input type="password" asp-for="Senha" id="senha" class="form-control" placeholder="Digite a senha do usuario">
        @Html.ValidationMessageFor(x => x.Senha)
    </div>
    <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
    <a class="btn btn-secondary btn-block" role="button" asp-action="Index" asp-controller="Contato">Voltar</a>
</form>

MeuSiteEmMVC/MeuSiteEmMVC/Views/Usuario/Editar.cshtml
@model UsuarioModel
@using MeuSiteEmMVC.Enums

@{
    ViewData["Title"] = "Editar usuário";
}

<div class="text-center">
    <h1 class="display-4">Editar Usuário</h1>
</div>
<form asp-action="Editar" asp-controller="Usuario" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="mb-3">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" asp-for="Nome" id="nome" class="form-control" placeholder="Digite o nome do usuario">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>
    <div class="mb-3">
        <label for="login" class="form-label">Login</label>
        <input type="text" asp-for="Login" id="login" class="form-control" placeholder="Digite o login do contato">
        @Html.ValidationMessageFor(x => x.Login)
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="text" asp-for="Email" id="email" class="form-control" placeholder="Digite o email do usuario">
        @Html.ValidationMessageFor(x => x.Email)
    </div>
    <div class="mb-3">
        <label for="perfil" class="form-label">Perfil</label>
        <select asp-for="Perfil" class="form-control" id="perfil">
            <option value="">Selecione</option>
            <option value="@PerfilEnum.Admin">Administrador</option>
            <option value="@PerfilEnum.Padrao">Padrão</option>
        </select>
        @Html.ValidationMessageFor(x => x.Perfil)
    </div>
    <button type="submit" class="btn btn-primary btn-block">Alterar</button>
    <a class="btn btn-secondary btn-block" role="button" asp-action="Index" asp-controller="Usuario">Voltar</a>
</form>

MeuSiteEmMVC/MeuSiteEmMVC/Views/Usuario/Index.cshtml
@model List<UsuarioModel>
@{
    ViewData["Title"] = "Listagem de Usuários";
}

<div class="text-center">
    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-3">
        <a class="btn btn-primary text-light" asp-controller="Usuario" asp-action="Criar" role="button">Adicionar novo usuario</a>
    </div>

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            @TempData["MensagemSucesso"]
        </div>
    }
    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["MensagemErro"]
        </div>
    }

    <h1 class="display-4">Listagem de usuários</h1>
    <table class="table" id="table-usuarios">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Login</th>
                <th scope="col">Email</th>
                <th scope="col">Perfil</th>
                <th scope="col">Data de cadastro</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (UsuarioModel usuario in Model)
                {
                    <tr>
                        <th scope="row">@usuario.Id</th>
                        <td>@usuario.Nome</td>
                        <td>@usuario.Login</td>
                        <td>@usuario.Email</td>
                        <td>@(usuario.Perfil == MeuSiteEmMVC.Enums.PerfilEnum.Admin ? "Admin" : "Padrão")</td>
                        <td>@usuario.DataCadastro</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" asp-controller="Usuario" asp-route-id="@usuario.Id" asp-action="Editar" class="btn btn-primary text-light">Editar</a>
                                <a role="button" asp-controller="Usuario" asp-route-id="@usuario.Id" asp-action="ApagarUsuario" class="btn btn-danger text-light">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>